# Generated by rust2rpm
%bcond_without check

%global crate ybaas

Name:           rust-%{crate}
Version:        0.0.1
Release:        3%{?dist}
Summary:        Yubibomb as a service

# Upstream license specification: GPL-3.0
License:        GPLv3
URL:            https://crates.io/crates/ybaas
Source:         %{crates_source}

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust-packaging
BuildRequires:  (crate(warp/default) >= 0.1.0 with crate(warp/default) < 0.2.0)
BuildRequires:  (crate(yubibomb/default) >= 0.2.0 with crate(yubibomb/default) < 0.3.0)

%global _description \
Don't you love when you accidentally tap your Yubikey when you have your IRC\
client in focus and you send 987947 into Freenode? Want to be able to have that\
experience without having to reach all the way over to your laptop's USB port?\
Don't want the complexity of installing and using the yubibomb CLI tool? Now\
you can use yubibomb as a service!

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}

%description -n %{crate} %{_description}

%files       -n %{crate}
%license LICENSE
%doc README.md CHANGELOG
%{_bindir}/ybaas

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Thu Jan 30 2020 Fedora Release Engineering <releng@fedoraproject.org> - 0.0.1-3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_32_Mass_Rebuild

* Fri Jul 26 2019 Fedora Release Engineering <releng@fedoraproject.org> - 0.0.1-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_31_Mass_Rebuild

* Thu Mar 14 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.0.1-1
- Initial package
